### ISSUE TITLE
Link to "Listen der validierten SARS-CoV-2-Schnelltests1.pdf"

### ISSUE THREAD

**Issue by dominikgehl** [admin-ch/CovidCertificate-Examples#6]
valuesets/README.md contains the following sentence:
"The valueset contains more tests than validated for Switzerland. This should be the whole list of the approved tests from the EU. For a list of approved tests in Switzerland, contact the "Listen der validierten SARS-CoV-2-Schnelltests1.pdf" file."

"contact" should probably be replaced with "consult", but I'm also missing this PDF document. Should it be part of the repo ? If not, could you add a link to it ?

**Comment by delixfe** [comment]
You find the information in <https://www.bag.admin.ch/bag/de/home/krankheiten/ausbrueche-epidemien-pandemien/aktuelle-ausbrueche-epidemien/novel-cov/information-fuer-die-aerzteschaft/covid-testung.html#1361999849> (in German). We will update the README.md.
